controller_manager:
  ros__parameters:

    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


arm_controller:
  ros__parameters:

    joints:
      - shoulder_pitch_joint
      - shoulder_roll_joint
      - shoulder_yaw_joint
      - elbow_pitch_joint
      - wrist_pitch_joint
      - wrist_roll_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.0

    action_monitor_rate: 20.0

    allow_partial_joints_goal: false

    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.5

      shoulder_pitch_joint:
        trajectory: 0.1
        goal: 0.05

      shoulder_roll_joint:
        trajectory: 0.1
        goal: 0.05

      shoulder_yaw_joint:
        trajectory: 0.1
        goal: 0.05

      elbow_pitch_joint:
        trajectory: 0.1
        goal: 0.05

      wrist_pitch_joint:
        trajectory: 0.1
        goal: 0.05

      wrist_roll_joint:
        trajectory: 0.1
        goal: 0.05